"""`agent-harness propose-upstream` — generate PR body draft for a candidate."""

from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: pip3 install pyyaml", file=sys.stderr)
    sys.exit(2)

from . import cmd_extract_candidate


PROPOSAL_TEMPLATE = """<!-- agent-harness upstream proposal draft
     Generated by: agent-harness propose-upstream (Phase E PR-E2)
     Generated at: {timestamp}
     Source file: {source_path}
     Consumer: {consumer_name}
-->

## PR 类型

- [x] 反哺（consumer → agent-harness core / adapter / preset）

## Summary

<!-- TODO: 一句话说明本 PR 的目的和内容 -->

---

## 反哺专用字段

### 起源

- Consumer 项目：{consumer_name}
- Consumer 触发 PR / issue：<!-- TODO: 填 PR 号或脱敏描述 -->
- 积累时间窗：{first_seen} ~ {last_seen}
- 有效使用次数：{commit_count} 次（git log --follow 统计）

### 已有使用证据

<!-- TODO: 描述在 consumer 里的使用场景 / 命中次数 / 节省的时间 / 防止的事故
     工具自动填写部分：
     - 文件：{source_path}
     - 首次提交：{first_seen}
     - 最近提交：{last_seen}
     - 总 commit 数：{commit_count}
-->

### P1 六门槛 checklist

- [ ] **two-consumer rule** — 第二类项目使用场景（见下方）
- [ ] **去项目化残余 = 0**（grep 报告见下方，工具扫描结果：{denylist_hits} 个 denylist 命中 + {consumer_term_hits} 个 consumer 术语命中）
- [ ] **通用性可配置**（diff 不含 `if project == X` 式分支）
- [ ] **可测试**（测试清单见下方）
- [ ] **低污染**（`core/` 无语言 / 产品特定术语）
- [ ] **生命周期清楚**（启用 / 退役 / 升级段见下方）

#### 第二 consumer 使用场景

<!-- TODO: ≥ 100 字。具体技术栈 + 调用方式 + 配置差异。
     反模式："这个很通用，任何项目都能用" -->

#### 去项目化 grep 报告

工具自动扫描结果（运行于生成时间 {timestamp}）：

```text
Denylist 命中: {denylist_hits}
Consumer terms 命中: {consumer_term_hits}
```

<!-- TODO: 修改文件去除 denylist / consumer term 后，重新跑 grep 粘贴真实结果 -->

```bash
$ grep -riE "<denylist-pattern>" <proposed-files>
# 手工确认：应为空
```

### P2 3 迭代周期

{p2_status}

**证据**：

git log 摘录：

```text
{source_path} - {commit_count} commits ({first_seen} → {last_seen})
```

<!-- TODO: 粘贴具体 git log 记录或关联 PR 清单 -->

### 安全级别

- [ ] **S-critical**（数据丢失 / 安全漏洞 / CI 绕过） — Safety Override 标注理由
- [x] **S-normal**（工具 / 方法论 / 质量门禁）<!-- 默认，按需改 -->
- [ ] 不确定 — 请 reviewer 判断

### 层分配

工具建议：**{suggested_layer}**

- [ ] `core/`（语言 / 工具 / agent 全无关）
- [ ] `adapter-<agent>/`（具体 agent 适配）
- [ ] `preset-<domain>/`（具体技术栈 preset）
- [ ] `examples/`

<!-- TODO: 勾选最终层分配 -->

### 测试

<!-- TODO: 新增 / 修改的测试清单。若豁免（纯文档 / 纯原则），说明理由 -->

### 迁移说明

<!-- TODO: 已有 consumer 如何 bump .agent-harness/lock.json 并适应本 PR 的 breaking change。
     如无 breaking 写 N/A -->

### 生命周期

- **启用条件**：<!-- TODO -->
- **退役条件**：<!-- TODO -->
- **升级路径**：<!-- TODO -->

---

## Test plan

- [ ] CI: markdownlint / shellcheck / denylist / core-tests 全绿
- [ ] <!-- TODO: 列出 PR 作者本地跑过的额外验证 -->

## 关联

<!-- 关联 issue / upstream 讨论 / RFC / cross-audit 归档等 -->

---

**Reviewer checklist**（由 reviewer 填）：

- [ ] Scope 合理（层分配正确，无 scope 蔓延）
- [ ] 去项目化验证通过（grep 0 命中 + CI denylist 绿）
- [ ] two-consumer rule 独立思考通过
- [ ] 可配置性 diff 扫描通过
- [ ] 测试覆盖合理
- [ ] 生命周期描述合理

详细 reviewer 流程见 [`docs/contracts/contribution-rubric.md`](../../docs/contracts/contribution-rubric.md) §5。
"""


def _p2_status(commit_count: int, min_iterations: int = 3) -> str:
    if commit_count >= min_iterations:
        return (
            f"- [x] consumer 已独立有效使用 {commit_count} 次（>= {min_iterations}）\n"
            "- [ ] 或申请 Safety Override（见 Safety-critical 段）"
        )
    return (
        f"- [ ] consumer 已独立有效使用 {commit_count} 次（**< {min_iterations}，不满足次门槛**）\n"
        "- [ ] 或申请 Safety Override（见 Safety-critical 段；如非 S-critical，建议留 overlay 继续积累）"
    )


def run(args: argparse.Namespace) -> int:
    consumer_root: Path = (args.target or Path.cwd()).resolve()
    project_yaml_path = consumer_root / ".agent-harness" / "project.yaml"
    if not project_yaml_path.is_file():
        print(
            f"ERROR: {project_yaml_path} not found. "
            "Run `agent-harness init` first or pass a valid --target.",
            file=sys.stderr,
        )
        return 2

    source_path_arg: Path = args.source
    # Resolve source relative to consumer_root if not absolute
    if source_path_arg.is_absolute():
        source_abs = source_path_arg.resolve()
    else:
        source_abs = (consumer_root / source_path_arg).resolve()

    if not source_abs.is_file():
        print(f"ERROR: source file not found: {source_abs}", file=sys.stderr)
        return 2

    try:
        source_rel = source_abs.relative_to(consumer_root)
    except ValueError:
        print(
            f"ERROR: source file must be inside consumer root ({consumer_root}). "
            f"Got: {source_abs}",
            file=sys.stderr,
        )
        return 2

    project_yaml = cmd_extract_candidate._load_project_yaml(consumer_root)
    consumer_name = project_yaml.get("project", {}).get("name") or consumer_root.name
    denylist = cmd_extract_candidate._resolve_denylist(project_yaml)
    consumer_terms = project_yaml.get("contribution", {}).get("consumer_terms", [])

    candidate = cmd_extract_candidate._build_candidate(
        source_abs, consumer_root, denylist, consumer_terms
    )

    timestamp = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")

    body = PROPOSAL_TEMPLATE.format(
        timestamp=timestamp,
        source_path=source_rel,
        consumer_name=consumer_name,
        first_seen=candidate.first_seen,
        last_seen=candidate.last_seen,
        commit_count=candidate.commit_count,
        denylist_hits=candidate.denylist_hits,
        consumer_term_hits=candidate.consumer_term_hits,
        suggested_layer=candidate.suggested_layer,
        p2_status=_p2_status(candidate.commit_count),
    )

    output_dir = consumer_root / ".agent-harness" / "proposals"
    output_dir.mkdir(parents=True, exist_ok=True)
    safe_stem = str(source_rel).replace("/", "__").replace(".", "_")
    output_path = output_dir / f"{safe_stem}__{timestamp.replace(':', '-')}.md"
    output_path.write_text(body, encoding="utf-8")

    print(f"agent-harness propose-upstream: {source_rel}")
    print()
    print(f"Proposal draft written to:")
    print(f"  {output_path.relative_to(consumer_root)}")
    print()
    print("Next steps:")
    print("  1. Open the draft and fill all TODO fields")
    print("  2. Manually verify去项目化 grep (must return 0)")
    print("  3. Think through the 'second consumer usage scenario' (>= 100 字)")
    print("  4. Open PR on agent-harness upstream with draft as body")
    print()
    if candidate.commit_count < 3:
        print(
            "NOTE: commit count < 3 iterations. Draft marks P2 as failing. "
            "Consider keeping in overlay unless this is S-critical."
        )
    return 0
