"""`agent-harness init` — scaffold consumer project."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: pip3 install pyyaml", file=sys.stderr)
    sys.exit(2)


PROJECT_YAML_TEMPLATE = """# agent-harness consumer project configuration
#
# See upstream templates/base/.agent-harness/project.yaml for full schema.
# Filled by `agent-harness init` ({tier} tier).

version: 1

project:
  name: "{name}"
  type: "{type}"
  repo: ""
  description: ""

upstream:
  repo: NotBad-Labs/agent-harness
  channel: main

presets: []

overlay_paths: {{}}

contribution:
  enabled: true
  scan_paths: []
"""


POLICY_STUB_TEMPLATE = """# docaudit policy stub — generated by `agent-harness init --pragmatic`
#
# Fill layout / scan / checks before running `docaudit all`.
# Schema reference: (upstream) core/tools/docaudit/policy.schema.yaml

version: 1

layout:
  rules_dir: ""
  principles_dir: ""
  rules_file: ""
  rule_id_pattern: '\\bRULE-(\\d{3})\\b'
  rule_header_pattern: '^#{1,4}\\s+RULE-(\\d{3})\\b'
  orphan_scan_dir: ""
  frontmatter_validator: null

scan:
  include: []
  exclude: []

checks:
  links:
    level: error
  archived-refs:
    level: error
    archived_sources: []
  orphans:
    level: warning
    whitelist: []
  home-path-refs:
    level: warning
    allowed_contexts: []
  rule-pointer-sync:
    level: error
    allowlist_rules: []
  rule-usage:
    level: info
    min_references: 1

legacy_whitelist: []

output:
  tsv_dir: "reports/"
"""


def _build_lock(upstream_commit: str) -> dict:
    return {
        "upstream_commit": upstream_commit,
        "channel": "main",
        "schema_version": 1,
    }


def run(args: argparse.Namespace) -> int:
    target: Path = args.target.resolve()
    if not target.is_dir():
        print(f"ERROR: target is not an existing directory: {target}", file=sys.stderr)
        return 2

    tier: str = args.tier
    project_name = args.project_name or target.name
    project_type = args.project_type

    ah_dir = target / ".agent-harness"
    if ah_dir.exists() and not args.force:
        # Check if key files exist; if both present, bail unless --force
        existing = [p.name for p in ah_dir.iterdir()]
        if "project.yaml" in existing or "lock.json" in existing:
            print(
                f"ERROR: {ah_dir} already contains agent-harness files. "
                f"Use --force to overwrite.",
                file=sys.stderr,
            )
            return 2

    ah_dir.mkdir(parents=True, exist_ok=True)

    # project.yaml
    project_yaml_path = ah_dir / "project.yaml"
    project_yaml_path.write_text(
        PROJECT_YAML_TEMPLATE.format(
            tier=tier,
            name=project_name,
            type=project_type,
        ),
        encoding="utf-8",
    )

    # lock.json
    lock_path = ah_dir / "lock.json"
    lock_path.write_text(
        json.dumps(_build_lock(args.upstream_commit), indent=2) + "\n",
        encoding="utf-8",
    )

    created = [project_yaml_path, lock_path]

    if tier == "pragmatic":
        # Additionally scaffold docaudit policy stub
        policy_dir = target / "Scripts" / "audit"
        policy_dir.mkdir(parents=True, exist_ok=True)
        policy_path = policy_dir / "policy.yaml"
        if policy_path.exists() and not args.force:
            print(
                f"WARN: {policy_path} already exists; skipping (use --force to overwrite).",
                file=sys.stderr,
            )
        else:
            policy_path.write_text(POLICY_STUB_TEMPLATE, encoding="utf-8")
            created.append(policy_path)

    print(f"agent-harness init --{tier} complete.")
    print(f"Target: {target}")
    print(f"Created {len(created)} files:")
    for path in created:
        rel = path.relative_to(target)
        print(f"  + {rel}")
    print()
    print("Next steps:")
    print("  1. Fill project.name / project.type / overlay_paths in .agent-harness/project.yaml")
    if tier == "pragmatic":
        print("  2. Fill layout / scan / checks in Scripts/audit/policy.yaml")
        print("  3. Run `agent-harness doctor` to verify setup")
    else:
        print("  2. Run `agent-harness doctor` to verify setup")
    print()
    print("  Pin upstream: `agent-harness sync --apply` (reserved; not in PR-D3)")
    return 0
